name: Makefile CI

on:
  push:
    branches: [ "lineage-18.1" ]
  pull_request:
    branches: [ "lineage-18.1" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: configure
      run: |

    - name: Install dependencies
      run: |

    - name: Run check
      run: make check

    - name: Run distcheck
      run: make distcheck
